"""DIMER inference package for the pinned ``Salesforce/blip-itm-base-coco`` checkpoint."""

from .pipeline import (
    DEFAULT_WEIGHTS_DIR,
    HOSTED_TF_WEIGHT_FILE,
    IMAGE_SIZE,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_IMAGES,
    MAX_TEXT_CHARS,
    MAX_TEXTS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    WEIGHT_FILE,
    BlipItmPipeline,
    evaluation_report,
    format_texts,
    recall_at_1,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DEFAULT_WEIGHTS_DIR",
    "HOSTED_TF_WEIGHT_FILE",
    "IMAGE_SIZE",
    "INPUT_SCHEMA",
    "MAX_IMAGES",
    "MAX_IMAGE_SIDE",
    "MAX_TEXTS",
    "MAX_TEXT_CHARS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "WEIGHT_FILE",
    "BlipItmPipeline",
    "evaluation_report",
    "format_texts",
    "recall_at_1",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
