"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, metrics.py, samples.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures an E2E image-text retrieval workflow: the pinned Salesforce/blip-itm-base-coco
snapshot is digest-verified and loaded, the captions of a digest-pinned VizWiz-Captions shard are read
column-only and the 672 photographs of its first two row groups are read the same way, validated and split
by image (row group 0 into train / validation / core test, row group 1 into the test gallery), three drawn
scenes are scored through the inference contract, the frozen model's retrieval over the 391-photograph gallery
is measured beside two non-neural baselines, a bounded fine-tuning of the text encoder's last blocks, both
projections and the ITM head runs, the gallery is scored again per category, the adapted model re-scores the
drawn scenes, and the adapter is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #10, ITM-M1..M5 / ITM-m1..m4): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); no held-out result is asserted (a kept epoch 0 is reported,
and the export still runs), and the notebook says that the recipe comparisons and the gallery size were decided with
test-gallery numbers, so the test delta is optimistic; every re-run of Sections 5-7 starts from the pretrained model;
the BYOD contract states the enforced minimum, replaces an earlier upload, keeps zip sub-folders under a guarded root
with size limits, names a missing records file, reports the BYOD gallery size and records BYOD provenance; every
measured figure names its run; and the guided layer (how to use, roadmap, predictions, worked answers, a
change-one-thing activity, troubleshooting, glossary, conclusion) is added.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "blip_itm_pipeline",
    "repo_name": "blip-itm-pipeline",
    "stem": "blip_itm",
    "notebook_name": "blip_itm_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml --python-version 3.12 --python-platform x86_64-manylinux_2_28 --generate-hashes
    # --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `Salesforce/blip-itm-base-coco` snapshot (an 895 MB `pytorch_model.bin` pickle, opened only after its "
        "SHA-256 matches and with `weights_only=True`), reads the four text columns of one digest-pinned VizWiz-Captions shard "
        "from the Hugging Face Hub (about 0.5 MB over HTTP range requests, no credential) and the image column of its first "
        "two row groups (672 photographs, about 166 MB in two range reads, each photograph refused on any size or SHA-256 "
        "mismatch), cuts row group 0 by image into 208 / 40 / 70 training, validation and core-test photographs and appends "
        "row group 1's 321 captioned photographs to the test gallery (391 photographs, 1,737 captions), scores three drawn "
        "scenes through the inference contract with an input manifest and a rejection probe, measures the frozen model's "
        "retrieval over the gallery (recall@1/5/10 in both directions, ITM re-ranking, ITM pair accuracy) beside the chance "
        "and colour-keyword baselines, runs a bounded fine-tuning of the text encoder's last two blocks, the two ITC "
        "projections and the ITM head with BLIP's contrastive and matching objectives and validation-rsum epoch selection, "
        "scores the gallery again per category, re-scores the drawn scenes with the adapted model, exports the adapter as "
        "safetensors with a manifest, and reloads that artifact into a fresh pipeline to verify score parity. The default "
        "path needs no repository clone, no DIMER worker or service, no credential, no upload dialog and no configuration "
        "edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used automatically when present. Measured times come from runs of "
        "the previous notebook version, whose model stages are the same: a local Windows CPU pre-flight (2026-09-19, "
        "float32, files pre-staged) took 1,512 s for the default path, and the Kaggle Tesla T4 run of 2026-09-19 took 387 s "
        "for its completing pass including the downloads. No hosted CPU run is recorded, so on a hosted CPU runtime expect "
        "roughly the CPU pre-flight figure (an estimate). Building the isolated environment and downloading the checkpoint "
        "come on top of these."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over). Supply one zip through the upload dialog on Colab, or a zip or folder "
        "path in `BYOD_PATH` on any runtime. It holds a `records.jsonl` (or `records.json`) of `{id, image, captions}` "
        "objects — `image` a path relative to the records file (sub-folders such as `photos/img_001.jpg` are kept), "
        "`captions` one or more distinct matching captions (the first is the retrieval query), optional `image_id` and "
        "`category` — beside the image files. It needs at least **12 records on 12 different images**, because the split "
        "by image must leave at least 8 training, 2 validation and 2 test records; Section 4 checks this before any model "
        "runs and names the split it refuses. A new upload replaces the previous one. The data passes through the same "
        "validation, seeded image-disjoint split, baselines, fine-tuning, held-out evaluation, artifact export and "
        "reload-parity cells as the VizWiz sample; Section 4 prints your test gallery's size, because recall@k depends on "
        "it. The expected schema and the ceilings are stated in the Prerequisites and in Section 4, and uploaded files stay "
        "inside this runtime. BYOD is optional and never part of the default path."
    ),
    "pipeline_class": "BlipItmPipeline",
    "weights_key": "blip-itm-base-coco",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "entry_module": "pipeline.py",
    "runtime_imports": ["torch", "transformers"],
    "title": "BLIP ITM-base — DIMER E2E image-text retrieval fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/blip-itm-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/blip-itm-pipeline/blob/main/tutorials/blip_itm_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Salesforce%2Fblip--itm--base--coco-ffcc4d?style=flat",
            "https://huggingface.co/Salesforce/blip-itm-base-coco",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-salesforce%2FBLIP-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/salesforce/BLIP",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2201.12086-b31b1b.svg", "https://arxiv.org/abs/2201.12086"),
    ],
    "capability": "image-text matching / retrieval and bounded supervised fine-tuning of the text encoder's last blocks, the ITC projections and the ITM head on a photograph/matching-captions dataset, using the pinned `Salesforce/blip-itm-base-coco` weights",
    "intro": (
        "`Salesforce/blip-itm-base-coco` is the BLIP model of Li et al. (2022) fine-tuned for image-text retrieval on COCO — "
        "a ViT-B/16 image encoder at 384×384 and a 12-layer BERT-style text encoder whose blocks also cross-attend to the "
        "image; 223,744,258 parameters, published under the **BSD-3-Clause** licence. It gives two scores per image–caption "
        "pair: the **ITC cosine** between the projected image and text embeddings (a dual-encoder score that can rank a "
        "gallery cheaply) and the **ITM probability** from a classifier head over the fused encoding (a per-pair score that "
        "is more accurate and far more expensive). **Neither score is calibrated and neither abstains**: a caption set with "
        "nothing that fits an image still yields a highest-scoring caption.\n\n"
        "What this notebook adds to inference is **adaptation with matching captions**. The dataset is real and out of the "
        "model's distribution: VizWiz-Captions (Gurari et al., ECCV 2020; **CC BY 4.0**) — photographs taken by blind "
        "people, each with up to five crowd-written captions that name what is held and what a label says — a population "
        "the model never saw. The notebook reads only the four text columns of one pinned Hub shard (about 0.5 MB over "
        "HTTPS range requests) and the image column of its **first two row groups** (672 photographs in two range reads, "
        "each pinned by size and SHA-256 in the carried module). Row group 0 is split by image into 208 / 40 / 70; row "
        "group 1's 321 captioned photographs join the **test gallery** so that retrieval is scored over 391 photographs "
        "and 1,737 captions — on a 70-photograph gallery the frozen model is already at the ceiling (the model card's build "
        "sweep measured rsum 5.72 of 6), and a gallery that small says nothing about adaptation. The honest question is "
        "narrow: does a bounded fine-tuning of the text encoder's last blocks, the projections and the ITM head on 208 "
        "photographs move recall over a real gallery, in which direction, and does the ITM re-ranking move with it? The "
        "retrieval protocol is implemented in the carried modules (**recall@1/5/10** in both directions with every caption "
        "in the gallery, **median rank**, **rsum**, **ITM pair accuracy** against the hardest wrong caption), and two "
        "**non-neural baselines** — **chance** and the **colour-keyword nearest neighbour** — show where a system with no "
        "model sits. Nothing here is a quality claim about your photographs: it is one seeded split of one corpus.\n\n"
        "**Weight-format note:** upstream hosts no SafeTensors at the pinned revision; the carried module executes the "
        "digest-pinned `pytorch_model.bin` (a pickle, deserialised with `weights_only=True` after its SHA-256 is checked), "
        "while the `tf_model.h5` upstream also hosts is DIMER's upload artifact and is never loaded here. Section 3 stages "
        "and digest-verifies the snapshot before the processor or the model is constructed.\n\n"
        "**Who this is for.** A learner who knows basic Python and has met the idea of an image model, and wants to see how a "
        "pretrained image-text retriever is measured over a gallery and adapted to a new kind of photograph. No prior "
        "experience with BLIP, retrieval metrics or fine-tuning is assumed; each term is explained where it is first used and "
        "again in the **Glossary** at the end.\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Scoring | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | images (16 to 4096 px a side) and distinct captions, scored as a grid | 208 training photographs, each with up to five matching captions |\n"
        "| Model | BLIP: ViT-B/16 image encoder + 12-layer text encoder; ITC projections and an ITM head | the same model with the text encoder's last 2 blocks, both projections and the ITM head trained |\n"
        "| Output | an ITM probability and an ITC cosine for every image–caption pair, and per-image rankings — no calibration, no abstention | an adapter (safetensors) and held-out recall@1/5/10, median rank, rsum and ITM pair accuracy |\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — the isolated environment, the carried code and the model verification — and "
        "can be run without study. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant "
        "to be edited; the defaults reproduce the recorded path. Each stage states what it does and asks you to **predict** "
        "before it runs, and the next cell opens with **What to notice** and a collapsible **Check your reasoning** block with "
        "a worked answer. Each optional experiment names the cell to change and the cells to re-run. Section 10 is a "
        "**change-one-thing activity**. **Troubleshooting**, a **Glossary** and a **Conclusion** template are at the end. Your "
        "notes are optional and are not required submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the photographs → 5 score drawn scenes with the pretrained model → 6 two "
        "baselines and the pretrained model's retrieval over the test gallery → 7 fine-tune the text encoder's last blocks, "
        "the projections and the ITM head → 8 compare on the held-out gallery → 9 re-score, export and reload → 10 **change "
        "one thing: a much higher learning rate** → conclude."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain the difference between the ITC cosine and the ITM probability and say "
        "why neither is calibrated (Section 5); (2) read recall@k in both directions, median rank and rsum over a gallery, "
        "say why a bigger gallery lowers them for the same model, and place the frozen model against two non-neural "
        "baselines (Section 6); (3) explain how validation, never test, chooses the kept epoch, and why reading recipe "
        "comparisons and the gallery design on the test split makes the test gain optimistic (Sections 7–8); (4) predict "
        "and then check which direction and which category of photograph gains after a bounded fine-tuning (Section 8); "
        "(5) predict and then observe what a much higher learning rate does to validation rsum and to the epoch the "
        "selector keeps (Section 10); and (6) check that an exported adapter reproduces the evaluated model (reload parity, "
        "Section 9)."
    ),
    "exclusions": (
        "captioning or question answering (separate checkpoints), retrieval over thousands of candidates with a precomputed "
        "index (the gallery here is 391 photographs, embedded in the session), reading text in the image (BLIP is not an OCR "
        "model, even though VizWiz captions transcribe labels), non-English captions, batch throughput, evaluation on COCO or "
        "Flickr30k (not bundled), fine-tuning of the vision encoder or the text embeddings, training on images that are not "
        "the pinned sample or your own uploads, and any claim that a VizWiz split stands in for your photographs. The "
        "repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab or Jupyter familiarity; no prior experience with BLIP, retrieval metrics or fine-tuning. The notebook explains the dual-encoder (ITC, contrastive) score and the fused-encoder (ITM, matching) score and why one is cheap and the other accurate, recall@k, median rank and rsum and why a small gallery inflates them, hard negatives, validation-based epoch selection and why a pickle checkpoint needs a digest check before `torch.load` where they are first used; the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own Python 3.12.12 environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter, and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path runs on CPU (float32) and uses CUDA automatically when available. The locked install (PyTorch 2.14.0 with its CUDA libraries) and the 895 MB checkpoint are the large downloads; the two row groups of photographs add about 166 MB. Measured on the previous notebook version, whose model stages are the same, in a local Windows CPU pre-flight (2026-09-19, float32, files pre-staged): about 236 s to embed and score the 391-photograph gallery with top-5 ITM re-ranking and 561 s for the four epochs of fine-tuning (888 photograph–caption pairs per epoch, three fused passes per pair for the matching loss, a 40-photograph validation pass per epoch); the whole default path took 1,512 s. The Kaggle Tesla T4 run of the same version took 387 s for its completing pass including the downloads. No hosted CPU run is recorded; expect roughly the CPU pre-flight figures there (an estimate).",
        "- **Data contract:** records are `{id, image, captions}` — an image file decodable by Pillow with sides between `MIN_IMAGE_SIDE` (16) and `MAX_IMAGE_SIDE` (4096) px and one or more distinct, non-empty matching captions of at most `MAX_TEXT_CHARS` (256) characters (`MIN_CAPTIONS` = 1; VizWiz supplies up to five; the first caption is the retrieval query); optional `image_id` (defaults to the id) groups records on the same image and optional `category` labels the breakdown (`text` / `no-text` in the sample, from the corpus's text-detected flag). Ids match `[A-Za-z0-9_.:-]{1,64}` and are unique; a dataset holds at most 5,000 records; every record on the same image lands in the same split so a test image is never trained on; every (image, caption) pair is one positive training sample and the batch supplies the negatives. The seeded split keeps about 20 % of the images for test and 15 % for validation and must leave at least 8 training, 2 validation and 2 test records, so a BYOD dataset needs at least **12 records on 12 different images** (more if several records share an image). Section 4 checks this before any model runs and names the split it refuses. Your test gallery is the test split only (about 20 % of your images), and recall@k over a small gallery is inflated: read the chance baseline beside it.",
        "- **BYOD layout:** one zip (by upload, or by path in `BYOD_PATH`; a folder path also works) holding exactly one `records.jsonl` or `records.json` and the images, with each `image` given relative to the records file — sub-folders are kept as written. The zip may hold at most 20,000 members and expand to at most 2 GB; links and members that would land outside the upload folder are refused before anything is written. A new upload replaces the files of the previous one.",
        "- **Validation is structural, not semantic:** every image is opened and decoded and every caption checked, but nothing checks that a caption matches its image — a mislabelled corpus is fine-tuned on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — photographs of people, documents or homes are exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path reads three parts of one object in the Hub dataset repository `mm-eval/VizWiz-Captions` at the immutable revision `c4a6d897…` (`data/val-00004-of-00005.parquet`, 392,245,504 bytes, SHA-256 `4492465a…`): the declared size and SHA-256 are checked against the pins before any byte is read; the four text columns of all 1,550 rows are fetched over HTTPS range requests through `pyarrow` (only the parquet footer and those column chunks) and refused unless their decoded SHA-256 matches; then the image column of row groups 0 and 1 only (672 JPEG files, about 166 MB) is read the same way, each photograph pinned by size and SHA-256 in the carried module and refused on any mismatch. The corpus is CC BY 4.0 (Gurari et al., 2020).",
    ],
    "cells": [
        {
            "md": (
                "## 4. VizWiz photographs, captions and split\n\n"
                "`fetch_annotations` reads the pinned shard's four text columns (or the cache under `weights/vizwiz-captions/`): "
                "it first checks the byte size and SHA-256 the Hub declares for the file against the pins, then reads only the "
                "parquet footer and those column chunks through `pyarrow` over HTTPS range requests, and refuses the decoded "
                "columns unless their SHA-256 matches. `fetch_images` stages the 672 pinned photographs of row groups 0 and 1 "
                "— each cached file is re-hashed; anything missing is read from its row group's image column in one range "
                "read and refused on any size or SHA-256 mismatch. `build_sample_dataset` keeps the photographs that carry at "
                "least one caption within the scoring ceiling (one caption of 1,391 in row group 0 is longer than 256 "
                "characters and is dropped; duplicates are removed), shuffles row group 0's 318 with `SPLIT_SEED` and cuts "
                "them **by image** into 208 / 40 / 70 training, validation and core-test records, then appends row group 1's "
                "321 captioned photographs to the test split as the gallery. Each record is labelled `text` or `no-text` "
                "from the corpus's text-detected flag. `validate_dataset` then opens and decodes every image and checks every "
                "record against the contract, `check_split_disjoint` asserts no image is shared, and the training split is "
                "written to `outputs/{stem}_train.jsonl` in the shape BYOD expects.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. The cell empties `work/byod/` first, so a second upload never reads the first one's files; it "
                "refuses a zip with more than 20,000 members, more than 2 GB expanded, a link or a member that would land outside "
                "`work/byod/`, before writing anything; it keeps sub-folders, so `image` paths are read relative to the records "
                "file; and an empty or cancelled upload, or a zip without `records.jsonl` / `records.json`, stops with a message "
                "saying what to supply. `split_dataset` then makes a seeded 65 / 15 / 20 % split **by image** and refuses a "
                "dataset that leaves fewer than 8 training, 2 validation or 2 test records, naming the split (at least 12 "
                "records on 12 different images). Under BYOD the printed provenance and `result.json` describe your upload, "
                "not the VizWiz corpus, and the cell prints the size of your test gallery: below 50 photographs the "
                "evaluation is labelled `measured-small-sample`, and recall@k there is inflated.\n\n"
                "Look for: 1,550 annotation rows, 672 photographs, three digests, the category mix per split (a little over "
                "half the photographs contain text), captions per image between 1 and 5, a 391-record test split whose "
                "gallery holds 1,737 captions, and four refusal probes — a duplicate id, a missing image file, a duplicated "
                "caption and a dataset too small to split — each rejected before `torch` does anything.\n\n"
                "**Predict before running:** a little over half of the photographs contain text (labels, screens, packaging). "
                "Will the 391-photograph test gallery have the same mix as the 208 training photographs, exactly or only roughly?"
            ),
            "code": (
                "import collections\n"
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "import shutil\n"
                "import stat\n"
                "import zipfile\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "MAX_ZIP_MEMBERS = 20_000\n"
                "MAX_ZIP_BYTES = 2_000_000_000\n"
                "RECORDS_NAMES = ('records.jsonl', 'records.json')\n\n\n"
                "def extract_zip(payload, root, label):\n"
                "    \"\"\"Extract an uploaded zip under root, keeping sub-folders and refusing the whole archive before writing anything unsafe.\"\"\"\n"
                "    base = root.resolve()\n"
                "    try:\n"
                "        archive = zipfile.ZipFile(io.BytesIO(payload))\n"
                "    except zipfile.BadZipFile:\n"
                "        raise ValueError(f'{{label}} is not a readable zip file: zip the records file and the images together and supply that zip.') from None\n"
                "    with archive:\n"
                "        members = archive.infolist()\n"
                "        expanded = sum(m.file_size for m in members)\n"
                "        if len(members) > MAX_ZIP_MEMBERS or expanded > MAX_ZIP_BYTES:\n"
                "            raise ValueError(f'{{label}} holds {{len(members)}} members and expands to {{expanded}} bytes; the limits are {{MAX_ZIP_MEMBERS}} members and {{MAX_ZIP_BYTES}} bytes, checked before anything is written.')\n"
                "        for member in members:\n"
                "            if stat.S_ISLNK(member.external_attr >> 16):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} is a symbolic link, which is not accepted; nothing was extracted.')\n"
                "            target = (root / member.filename).resolve()\n"
                "            if target == base or not target.is_relative_to(base):\n"
                "                raise ValueError(f'{{label}}: zip member {{member.filename!r}} would land outside the upload folder; nothing was extracted.')\n"
                "        for member in members:\n"
                "            if not member.is_dir():\n"
                "                target = (root / member.filename).resolve()\n"
                "                target.parent.mkdir(parents=True, exist_ok=True)\n"
                "                target.write_bytes(archive.read(member))\n\n\n"
                "def find_records_file(root, label):\n"
                "    found = sorted(p for p in Path(root).rglob('*') if p.name in RECORDS_NAMES and '__MACOSX' not in p.parts)\n"
                "    if not found:\n"
                "        raise ValueError(f'No records.jsonl or records.json found in {{label}}. Put one records file of {{{{id, image, captions}}}} objects beside the images (image paths relative to it), then run this cell again.')\n"
                "    if len(found) > 1:\n"
                "        raise ValueError(f'{{label}} holds more than one records file; keep exactly one of: ' + ', '.join(str(p.relative_to(root)) for p in found))\n"
                "    return found[0]\n\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    byod_root = Path('work') / 'byod'\n"
                "    if byod_root.exists():\n"
                "        shutil.rmtree(byod_root)  # a new upload never reads files left by an earlier one\n"
                "    byod_root.mkdir(parents=True)\n"
                "    payload = None\n"
                "    if BYOD_PATH.strip():\n"
                "        source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name = source.name\n"
                "        if source.is_dir():\n"
                "            records_file = find_records_file(source, str(source))\n"
                "        elif source.suffix.lower() == '.zip':\n"
                "            payload = source.read_bytes()\n"
                "            extract_zip(payload, byod_root, file_name)\n"
                "            records_file = find_records_file(byod_root, file_name)\n"
                "        else:\n"
                "            raise ValueError(f'BYOD_PATH must name a .zip or a folder holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise RuntimeError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        if not file_name.lower().endswith('.zip'):\n"
                "            raise ValueError(f'Upload a .zip holding records.jsonl / records.json and the images, not {{file_name!r}}.')\n"
                "        extract_zip(payload, byod_root, file_name)\n"
                "        records_file = find_records_file(byod_root, file_name)\n"
                "    records = load_byod_dataset(records_file)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED, base_dir=records_file.parent)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "    byod = {{'file': file_name, 'records_file': records_file.name, 'records': len(records), 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None, 'minimum_records': byod_minimum_records()}}\n"
                "else:\n"
                "    annotations = fetch_annotations(cache_dir='weights/vizwiz-captions')\n"
                "    image_paths = fetch_images(sorted(IMAGE_PINS), cache_dir='weights/vizwiz-captions')\n"
                "    raw_rows = {{'annotations': len(annotations), 'photographs': len(image_paths), 'row_groups': CORPUS_FILE['row_groups']}}\n"
                "    splits = build_sample_dataset(annotations, seed=SPLIT_SEED, image_paths=image_paths)\n"
                "    data_source = f'{{CORPUS_NAME}} {{CORPUS_RELEASE}} ({{CORPUS_LICENSE}})'\n"
                "dataset_manifests = {{name: validate_dataset(part, min_records=MIN_RECORDS if name == 'train' else 1) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "categories = {{name: manifest['categories'] for name, manifest in dataset_manifests.items()}}\n"
                "gallery_texts, gallery_owners = gallery(test_records)\n"
                "write_dataset_jsonl(splits['train'], 'outputs/{stem}_train.jsonl')\n"
                "if USE_BYOD:\n"
                "    test_gallery = {{'photographs': len(test_records), 'captions': len(gallery_texts), 'chance_t2i_recall_at_1': round(1 / len(test_records), 3), 'label': 'measured' if len(test_records) >= MIN_SCORED_RECORDS else 'measured-small-sample'}}\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'test_gallery': test_gallery, 'byod': byod}})\n"
                "else:\n"
                "    print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'gallery_captions': len(gallery_texts), 'text_sha256': CORPUS_FILE['text_sha256'][:16] + '...', 'pinned_photographs': len(IMAGE_PINS)}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'unique_images': manifest['unique_images'], 'categories': manifest['categories'], 'captions_per_image': manifest['captions_per_image'], 'caption_words': manifest['caption_words'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = splits['train'][0]\n"
                "print({{'example': {{'id': example['id'], 'image': Path(example['image']).name, 'size': example['image_size'], 'category': example['category'], 'query': query_caption(example), 'captions': len(example['captions'])}}}})\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in splits['train'][:8]],\n"
                "    'missing image file': [{{**splits['train'][0], 'image': 'work/does-not-exist.jpg'}}, *splits['train'][1:8]],\n"
                "    'duplicated caption': [{{**splits['train'][0], 'captions': [splits['train'][0]['captions'][0]] * 2}}, *splits['train'][1:8]],\n"
                "    'too small': splits['train'][:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes, the category counts per split, the 1,737 gallery captions, and that "
                "the splits share no image.\n\n"
                "<details><summary>Check your reasoning</summary>Only roughly. The split shuffles whole images with a seed and "
                "cuts the list by count, and the gallery's extra 321 photographs come from a different row group; nothing "
                "stratifies by category. In the recorded runs of the previous notebook version (same seed) `text` held 110 of the "
                "208 training photographs (53 %), 25 of the 40 validation photographs and 231 of the 391 gallery photographs "
                "(59 %). That is close enough to read the per-category scores later, but the 40-photograph validation split is "
                "small — which matters for the epoch it picks in Section 7.</details>\n\n"
                "## 5. Score through the inference contract\n\n"
                "The inference contract is exercised as the inference-only tutorial exercised it: three flat cartoon scenes — "
                "a red house with a tree, a beach with a red sailboat, an apple and an orange on a table — are drawn in code "
                "with Pillow (no text rendering, so their digests are stable across builds) with one authored caption each, "
                "a different image family from the photographs, and a grid the model will score again after adaptation. "
                "`validate_inputs` applies exactly the checks `score` applies (image sides `MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE`, "
                "at most `MAX_IMAGES` × `MAX_TEXTS` distinct captions of up to `MAX_TEXT_CHARS`) and returns an input "
                "manifest; a duplicated caption is validated too and its rejection recorded as a finding. `score` returns the "
                "`itm_probability`, `itm_logit_match` and `cosine` grids plus per-image rankings. **Neither score is "
                "calibrated and neither abstains** — the ITM probability is a per-pair classifier output, the cosine is "
                "comparable only within a row or column, and a caption set with nothing that fits still produces a "
                "highest-scoring caption. The per-image `evaluation_report` on the 3×3 grid is `sample-sanity` — three "
                "authored pairs carry no dispersion; whether the model retrieves *well* is what Section 6 measures over 391 "
                "photographs.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *before* or *frozen* number is "
                "never read from the adapted model.\n\n"
                "**Predict before running:** will each drawing's own caption score highest in its row? And will the ITM "
                "probability of the right caption be close to 1 for all three drawings?"
            ),
            "code": (
                "import gc\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = BlipItmPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "def synthetic_scenes():\n"
                "    \"\"\"Three flat cartoon scenes drawn with Pillow (no text); returns [(name, image, authored caption)].\"\"\"\n"
                "    house = Image.new('RGB', (640, 480), (135, 206, 235))  # sky\n"
                "    d = ImageDraw.Draw(house)\n"
                "    d.rectangle([0, 300, 640, 480], fill=(60, 179, 75))  # grass\n"
                "    d.ellipse([500, 40, 600, 140], fill=(255, 215, 0))  # sun\n"
                "    d.rectangle([120, 180, 320, 330], fill=(200, 40, 40))  # red house\n"
                "    d.polygon([(100, 180), (220, 90), (340, 180)], fill=(90, 50, 20))  # brown roof\n"
                "    d.rectangle([200, 260, 240, 330], fill=(70, 40, 20))  # brown door\n"
                "    d.ellipse([420, 260, 520, 360], fill=(40, 100, 40))  # tree crown\n"
                "    d.rectangle([460, 350, 480, 420], fill=(90, 60, 30))  # trunk\n"
                "    d.ellipse([60, 380, 140, 440], fill=(255, 255, 255))  # white ball\n"
                "    beach = Image.new('RGB', (640, 480), (120, 190, 240))  # sky\n"
                "    d = ImageDraw.Draw(beach)\n"
                "    d.rectangle([0, 220, 640, 330], fill=(30, 110, 200))  # sea\n"
                "    d.rectangle([0, 330, 640, 480], fill=(238, 214, 150))  # sand\n"
                "    d.ellipse([60, 40, 150, 130], fill=(255, 230, 80))  # sun\n"
                "    d.polygon([(400, 330), (470, 330), (435, 210)], fill=(230, 40, 40))  # red sail\n"
                "    d.rectangle([432, 210, 438, 330], fill=(90, 60, 30))  # mast\n"
                "    d.ellipse([200, 370, 260, 430], fill=(255, 120, 40))  # beach ball\n"
                "    fruit = Image.new('RGB', (480, 480), (250, 250, 245))\n"
                "    d = ImageDraw.Draw(fruit)\n"
                "    d.ellipse([60, 120, 220, 280], fill=(220, 30, 30))  # red apple\n"
                "    d.rectangle([135, 95, 145, 125], fill=(80, 50, 20))  # stalk\n"
                "    d.ellipse([250, 140, 430, 300], fill=(255, 170, 20))  # orange\n"
                "    d.polygon([(90, 400), (400, 400), (360, 330), (130, 330)], fill=(180, 120, 60))  # table\n"
                "    return [\n"
                "        ('synthetic_house_640x480.png', house, 'a red house with a tree under a blue sky'),\n"
                "        ('synthetic_beach_640x480.png', beach, 'a sailboat on the sea next to a beach'),\n"
                "        ('synthetic_fruit_480x480.png', fruit, 'an apple and an orange on a wooden table'),\n"
                "    ]\n\n\n"
                "reset_to_pretrained()\n"
                "scenes = synthetic_scenes()\n"
                "scene_names = [name for name, _, _ in scenes]\n"
                "scene_images = [image for _, image, _ in scenes]\n"
                "scene_texts = [caption for _, _, caption in scenes]\n"
                "correct_text_per_image = list(range(len(scenes)))  # caption i describes image i\n"
                "scene_digests = {{name: hashlib.sha256(np.asarray(image.convert('RGB')).tobytes()).hexdigest() for name, image in zip(scene_names, scene_images)}}\n"
                "ceilings = {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'IMAGE_SIZE': IMAGE_SIZE, 'MAX_IMAGES': MAX_IMAGES, 'MAX_TEXTS': MAX_TEXTS, 'MAX_TEXT_CHARS': MAX_TEXT_CHARS, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'MIN_CAPTIONS': MIN_CAPTIONS, 'MAX_CAPTION_CHARS': MAX_CAPTION_CHARS}}\n"
                "print(ceilings)\n"
                "input_manifest = validate_inputs(scene_images, scene_texts, names=scene_names)\n"
                "try:\n"
                "    validate_inputs(scene_images, [scene_texts[0], '  ' + scene_texts[0] + ' '])\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'duplicate-caption-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'scenes': scene_names, 'rgb_sha256': {{k: v[:16] + '...' for k, v in scene_digests.items()}}, 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n"
                "t0 = time.perf_counter()\n"
                "result = pipe.score(scene_images, scene_texts)\n"
                "np.set_printoptions(precision=3, suppress=True)\n"
                "print({{'seconds': round(time.perf_counter() - t0, 2), 'pairs': result['n_images'] * len(result['texts'])}})\n"
                "print('itm_probability [image][text]:')\n"
                "print(result['itm_probability'])\n"
                "print('cosine [image][text]:')\n"
                "print(result['cosine'])\n"
                "checks = {{\n"
                "    'grid_shape': result['itm_probability'].shape == (len(scenes), len(scene_texts)),\n"
                "    'probabilities_in_range': bool(np.all((result['itm_probability'] >= 0) & (result['itm_probability'] <= 1))),\n"
                "    'cosines_finite': bool(np.all(np.isfinite(result['cosine']))),\n"
                "    'one_ranking_per_image': len(result['rankings']) == len(scenes),\n"
                "}}\n"
                "if not all(checks.values()):\n"
                "    raise RuntimeError(f'score output failed a sanity check: {{checks}}')\n"
                "frozen_scene = evaluation_report(result, correct_text_per_image, sample_kind='synthetic')\n"
                "print({{'checks': checks, 'frozen_scene': {{m['id']: round(m['value'], 3) for m in frozen_scene['metrics']}}, 'verdict': frozen_scene['verdict']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the diagonal of each grid against the off-diagonal entries, and that nothing in the output "
                "says how sure the model is.\n\n"
                "<details><summary>Check your reasoning</summary>Yes to the first, no to the second. In the model card's CPU "
                "smoke and the recorded runs of the previous notebook version every drawing's own caption ranked first by both "
                "scores, but the ITM probability of the right caption was 0.998 for the house, 0.634 for the beach and only "
                "0.278 for the fruit scene. A correct match can get a low probability and, on a caption set with nothing that "
                "fits, a wrong one still gets the highest: the probability is a classifier output, not a calibrated confidence, "
                "and the cosine is only comparable within a row or a column. Three drawings are an observation about the "
                "contract, not a measurement of quality.</details>\n\n"
                "## 6. Baselines and the frozen model's retrieval over the gallery\n\n"
                "Three systems frame the adaptation. **Chance** is the analytical expectation of a random ranking over the "
                "same gallery (recall@k ≈ k / 391 in the text-to-image direction). The **colour-keyword nearest neighbour** "
                "retrieves with no model: text → image through the query's closest training caption by bag-of-words F1 and "
                "that photograph's 3×3 mean-colour grid; image → text through the colour-nearest training photograph's "
                "captions. The **frozen model** is scored by `pipe.evaluate`: every caption of every test record is the "
                "gallery (1,737 captions for 391 photographs), the ITC cosine grid gives **recall@1/5/10** in both directions "
                "(image → text counts a hit when any of the photograph's own captions is in the top k), **median rank** and "
                "**rsum** (the sum of the six recalls, 0..6); then the ITM head re-ranks each photograph's top-`RERANK_TOP_K` "
                "captions and each query caption's top-`RERANK_TOP_K` photographs (`itm_i2t_recall_at_1`, "
                "`itm_t2i_recall_at_1`) and is scored on **ITM pair accuracy** — each photograph's query caption against the "
                "hardest wrong caption by ITC. The cell reloads the pretrained model first if an earlier pass adapted it, and "
                "refuses to report an adapted model as frozen. It prints whether the frozen model beats the two baselines "
                "instead of asserting it: on your own photographs that is a result to read. In the local CPU pre-flight of the "
                "previous notebook version this cell took about 236 s.\n\n"
                "**Predict before running:** where will the frozen model's rsum land relative to the two baselines? Which "
                "direction will be easier, image → text or text → image? And which category, `text` or `no-text`?"
            ),
            "code": (
                "RERANK_TOP_K = 5  # @param {{type:\"integer\"}}\n\n"
                "reset_to_pretrained()\n"
                "baseline_chance = chance_baseline(test_records)\n"
                "baseline_neighbour = colour_keyword_baseline(train_records, test_records)\n"
                "METRICS = ('i2t_recall_at_1', 'i2t_recall_at_5', 'i2t_recall_at_10', 't2i_recall_at_1', 't2i_recall_at_5', 't2i_recall_at_10', 'rsum')\n"
                "ITM_METRICS = ('itm_i2t_recall_at_1', 'itm_t2i_recall_at_1', 'itm_pair_accuracy')\n"
                "print({{'chance_baseline': {{k: round(baseline_chance[k], 3) for k in METRICS}}, 'n': baseline_chance['n_images'], 'note': baseline_chance['baseline']}})\n"
                "print({{'colour_keyword_baseline': {{k: round(baseline_neighbour[k], 3) for k in METRICS}}, 'note': baseline_neighbour['baseline']}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, rerank_top_k=RERANK_TOP_K)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{k: round(frozen_test[k], 3) for k in METRICS}}, 'itm': {{k: round(frozen_test[k], 3) for k in ITM_METRICS}}, 'median_rank': [frozen_test['i2t_median_rank'], frozen_test['t2i_median_rank']], 'n': [frozen_test['n_images'], frozen_test['n_captions']], 'verdict': frozen_test['verdict'], 'adapted': frozen_test['adapted'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'frozen_above_baselines': {{'chance': frozen_test['rsum'] > baseline_chance['rsum'], 'colour_keyword': frozen_test['rsum'] > baseline_neighbour['rsum']}}}})\n"
                "print({{'definitions': METRIC_DEFINITIONS}})\n"
                "frozen_fields = frozen_test['by_category']  # each category scored as its own sub-gallery of the same grid\n"
                "print({{'by_category_frozen': frozen_fields}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the gap between the baselines and the frozen model, `adapted: False`, the two directions, "
                "and the per-category line.\n\n"
                "<details><summary>Check your reasoning</summary>Far above both. In the recorded runs of the previous notebook "
                "version chance scored rsum 0.082 and the colour-keyword neighbour 0.132, while the frozen model scored 5.024 of "
                "6 (image → text R@1 0.742, text → image R@1 0.652): a trained retriever matches meaning, which no colour lookup "
                "can. Image → text is easier because a photograph has up to five captions in the gallery and any of them counts, "
                "while a caption must find its one photograph among 391. The `text` photographs (labels, screens, packaging) "
                "were harder (0.73 / 0.63) than the `no-text` ones (0.81 / 0.78): their captions name what a label says, which "
                "the model cannot read. And the gallery size matters more than any of this: the same frozen model scored rsum "
                "5.72 on the 70-photograph core test split and 5.02 on 391 photographs — more candidates, more ways to rank a "
                "wrong one first, with no change to the model.</details>\n\n"
                "## 7. Bounded fine-tuning of the text encoder's last blocks, the projections and the ITM head\n\n"
                "`pipe.adapt` trains only the last `TRAINABLE_TEXT_LAYERS` blocks of the fused text encoder (self-attention, "
                "cross-attention to the image and feed-forward), the two ITC projections and the ITM head — two blocks by "
                "default, 19,298,818 of 223,744,258 parameters; the vision encoder and the text embeddings stay frozen. The "
                "frozen vision encoder's output is computed **once** per training photograph and reused across epochs. Every "
                "(photograph, caption) pair is one sample, 888 per epoch here, and a batch of 16 trains BLIP's two "
                "objectives: the **image-text contrastive loss** (symmetric cross-entropy over the in-batch cosine "
                "similarities at temperature 0.07, pairs of the same photograph counted as positives) and the **image-text "
                "matching loss** (the ITM head on the batch's positives plus one **hard negative** caption per photograph and "
                "one hard negative photograph per caption, sampled in proportion to their ITC similarity, never from the same "
                "photograph). AdamW at a fixed learning rate, gradient clipping at 1.0, seeded shuffling and no scheduler. "
                "Epoch 0 records the frozen model's validation retrieval; every epoch is scored on the 40 validation "
                "photographs by ITC rsum, and the epoch with the highest **validation** rsum is kept — the test gallery plays no "
                "part in that choice. A 40-photograph gallery saturates near 5.9 of 6, so that selection is weakly informed, "
                "which is why the 391-photograph gallery in Section 8 is what the numbers are read from. The four epochs took "
                "561 s in the local CPU pre-flight of the previous notebook version; much less on a GPU.\n\n"
                "**How the recipe and the gallery were chosen — read this before Section 8.** Before the notebook was written, "
                "the build record compared recipes **by their score on the test gallery** (the model card records it: two blocks "
                "at 2e-5 for four epochs reached rsum 5.158 and four blocks at 5e-5 for six epochs 5.157; on the earlier "
                "70-photograph test split 5.757 against 5.721 frozen), and the gallery was enlarged from 70 to 391 photographs "
                "after the frozen model's test score was seen at the ceiling. So although this run never looks at the test "
                "split to choose anything, the default recipe and the gallery design were decided with test numbers, and the "
                "Section 8 gain is an **optimistic** number rather than independent evidence. An independent estimate would "
                "need the comparison repeated on the validation split (or a development split carved from training) and a test "
                "gallery nobody had looked at.\n\n"
                "**Adaptation always starts from the pretrained model.** If this cell runs again (for example with "
                "`LEARNING_RATE = 1e-3` in Section 10), it first reloads the pretrained model from the verified snapshot, so the "
                "new training never stacks on the previous one, epoch 0 really is the frozen model, and the exported adapter holds "
                "exactly what this run trained; `pipe.adapt` itself refuses a model that is already adapted.\n\n"
                "**Predict before running:** will validation rsum rise in every epoch? Which epoch will be kept?"
            ),
            "code": (
                "EPOCHS = 4  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 2e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 16  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_TEXT_LAYERS = 2  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_' + k: round(entry['val'][k], 3) for k in ('i2t_recall_at_1', 't2i_recall_at_1', 'rsum')}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_text_layers=TRAINABLE_TEXT_LAYERS, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'training_pairs': adapt_result['n_pairs'], 'itc_temperature': adapt_result['itc_temperature'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, the validation rsum moves by hundredths and does not "
                "climb steadily, and the kept epoch is the one with the highest validation score.\n\n"
                "<details><summary>Check your reasoning</summary>No. In the recorded runs of the previous notebook version the "
                "validation rsum went 5.816 → 5.855 → 5.886 → 5.861 → 5.861 over epochs 0–4 while the training loss kept "
                "falling: it peaked in epoch 2 and epoch 2 was kept. The 40-photograph validation gallery is close to its "
                "ceiling of 6, so the differences are a few photographs. If the score had never risen above epoch 0, the rule "
                "would have kept epoch 0 — the frozen weights — and that would be a legitimate result, not an error (Section 10 "
                "shows one).</details>\n\n"
                "## 8. Held-out evaluation over the gallery\n\n"
                "In this run the test photographs were never used for training or epoch selection, and no test image appears in "
                "the training or validation splits. The recipe comparisons and the gallery size, however, were decided in the "
                "build record with test-gallery numbers (Section 7), so read the delta below as **optimistic**. The adapted model "
                "is scored exactly as the frozen model was in Section 6, the four systems are put side by side on the six "
                "recalls and rsum, the ITM re-ranking and pair accuracy are repeated, and the per-category recall@1 is repeated. "
                "Read it in this order: **rsum** first (the number the epoch was selected on), then **image → text R@1** and "
                "**text → image R@1**, then the ITM re-ranking and the ITM pair accuracy. The cell prints a verdict — "
                "*improved*, *not improved*, or *the selector kept epoch 0* — and carries on either way: a flat or negative "
                "result from an experiment is a result to read, not an error, and the export in Section 9 still runs. It also "
                "keeps a **run history** for this session, one row per pass through Section 8, so an experiment can be compared "
                "with the default run (Section 10). One seeded split of one corpus gives **no dispersion estimate**; the deltas "
                "are sample-sanity evidence that the adaptation contract works, not a benchmark, and a gain on VizWiz says "
                "nothing about your photographs until you measure it there.\n\n"
                "**Predict before running:** which direction will gain more, image → text or text → image? Will the ITM pair "
                "accuracy move? Will the gain be spread evenly over the `text` and `no-text` photographs?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, rerank_top_k=RERANK_TOP_K)\n"
                "adapted_val = pipe.evaluate(val_records)\n"
                "adapted_fields = adapted_test['by_category']\n"
                "comparison = {{metric: {{'chance': round(baseline_chance[metric], 3), 'neighbour': round(baseline_neighbour[metric], 3), 'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in METRICS}}\n"
                "comparison['itm'] = {{metric: {{'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in ITM_METRICS}}\n"
                "comparison['median_rank'] = {{'frozen': [frozen_test['i2t_median_rank'], frozen_test['t2i_median_rank']], 'adapted': [adapted_test['i2t_median_rank'], adapted_test['t2i_median_rank']]}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 3) for metric in METRICS + ITM_METRICS}}\n"
                "comparison['by_category'] = {{category: {{'n': frozen_fields[category]['n'], 'frozen': [round(frozen_fields[category]['i2t_recall_at_1'], 3), round(frozen_fields[category]['t2i_recall_at_1'], 3)], 'adapted': [round(adapted_fields[category]['i2t_recall_at_1'], 3), round(adapted_fields[category]['t2i_recall_at_1'], 3)]}} for category in frozen_fields}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n"
                "delta_rsum = adapted_test['rsum'] - frozen_test['rsum']\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    verdict = f'the selector kept epoch 0 (the frozen weights): no epoch beat the frozen validation rsum, so the adapted model is the frozen model and the test rsum delta is {{delta_rsum:.3f}}'\n"
                "elif delta_rsum > 0:\n"
                "    verdict = f'improved: the adapted test rsum is {{delta_rsum:.3f}} above the frozen one (optimistic: the recipe comparisons and the gallery size were decided with test numbers)'\n"
                "else:\n"
                "    verdict = f'not improved: the adapted test rsum is {{delta_rsum:.3f}} relative to the frozen one (read it; the notebook carries on)'\n"
                "print({{'best_epoch': adapt_result['best_epoch'], 'verdict': verdict}})\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'layers': TRAINABLE_TEXT_LAYERS, 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'rerank': RERANK_TOP_K, 'best_epoch': adapt_result['best_epoch'], 'frozen_rsum': round(frozen_test['rsum'], 3), 'adapted_rsum': round(adapted_test['rsum'], 3), 'delta': round(delta_rsum, 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'layers':>6}} {{'epochs':>6}} {{'lr':>8}} {{'rerank':>6}} {{'best':>4}} {{'frozen':>7}} {{'adapted':>7}} {{'delta':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['layers']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['rerank']:>6}} {{h['best_epoch']:>4}} {{h['frozen_rsum']:>7.3f}} {{h['adapted_rsum']:>7.3f}} {{h['delta']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'categories': categories,\n"
                "    'gallery': {{'photographs': len(test_records), 'captions': len(gallery_texts)}},\n"
                "    'rerank_top_k': RERANK_TOP_K,\n"
                "    'baselines': {{'chance': baseline_chance, 'colour_keyword': baseline_neighbour}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'verdict': verdict,\n"
                "    'selection': {{'metric': 'validation rsum (ITC cosine)', 'split': 'validation', 'best_epoch': adapt_result['best_epoch'], 'recipe_and_gallery_chosen_with': 'test-gallery numbers, in the build-record sweep (see MODEL_CARD.md); the test delta is optimistic'}},\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta row, the ITM rows, the per-category line, the verdict and the run history.\n\n"
                "<details><summary>Check your reasoning</summary>Image → text gains more. In the local CPU pre-flight of the "
                "previous notebook version rsum rose 5.024 → 5.162, image → text R@1 0.742 → 0.791 (0.803 → 0.844 after ITM "
                "re-ranking) and text → image R@1 only 0.652 → 0.673; the Kaggle T4 run of the same version gave 5.024 → 5.157, "
                "0.742 → 0.790 (0.803 → 0.841) and 0.652 → 0.672 — the third decimal differs between CPU and GPU arithmetic. "
                "The ITM pair accuracy barely moved: 0.683 → 0.688 on the CPU run and 0.683 → 0.683 on the T4 run, a change "
                "no larger than that arithmetic difference; the ITM head was already the better judge of hard pairs. The gain "
                "sat on the `text` photographs (image → text 0.732 → 0.797 on CPU, 0.801 on the T4) while the `no-text` ones "
                "stayed at 0.812: the adapted text encoder matches VizWiz's caption style, which names what a label says. "
                "Remember that the delta is optimistic (Section 7) and has no dispersion estimate: it shows the contract works, "
                "not by how much the model improved.</details>\n\n"
                "## 9. Re-score the drawn scenes, export the adapter and reload it\n\n"
                "The 3×3 grid from Section 5 is scored again by the adapted model — drawings, a different image family from the "
                "photographs it was tuned on, so this is a small look at what the adaptation did *outside* its corpus; a changed "
                "ranking here is a finding to record, not a failure — and reported with the per-image `evaluation_report` "
                "(`sample-sanity`). Both grids are written as CSV.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the text encoder's last two blocks, the two projections and "
                "the ITM head by default, about 77 MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact "
                "format, the base model id and revision, the digest of the base `pytorch_model.bin`, the tensor names, the file "
                "size and SHA-256, the training configuration, the kept epoch and the epoch history (OUT8). When the selector "
                "kept epoch 0 the exported tensors equal the base model's, and the manifest says so through `best_epoch: 0`. "
                "`BlipItmPipeline.from_artifact` re-verifies the base snapshot, checks the artifact manifest, its digest and its "
                "exact tensor set **before** deserialising, refuses any tensor outside the text encoder blocks, the projections "
                "and the ITM head, and overlays the tensors onto a freshly loaded base — a new object from files, not the "
                "in-memory model (VER2). The cell checks for identical cosine grids on up to eight test photographs against "
                "their query captions (VER4) and stops with an explanation if they differ. Under BYOD `result.json` records your "
                "upload in place of the VizWiz corpus block.\n\n"
                "**Predict before running:** will the adapted model still rank each drawing's own caption first? Will the fruit "
                "scene's ITM probability go up or down?"
            ),
            "code": (
                "import csv\n\n"
                "adapted_result = pipe.score(scene_images, scene_texts)\n"
                "adapted_scene = evaluation_report(adapted_result, correct_text_per_image, sample_kind='synthetic')\n"
                "print('adapted itm_probability [image][text]:')\n"
                "print(adapted_result['itm_probability'])\n"
                "print({{'scene_after_adaptation': {{m['id']: round(m['value'], 3) for m in adapted_scene['metrics']}}, 'verdict': adapted_scene['verdict']}})\n"
                "with open('outputs/{stem}_scores.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.writer(handle)\n"
                "    writer.writerow(['image', 'text', 'frozen_itm_probability', 'frozen_cosine', 'adapted_itm_probability', 'adapted_cosine'])\n"
                "    for i, name in enumerate(scene_names):\n"
                "        for j, text in enumerate(scene_texts):\n"
                "            writer.writerow([name, text, f\"{{result['itm_probability'][i, j]:.4f}}\", f\"{{result['cosine'][i, j]:.4f}}\", f\"{{adapted_result['itm_probability'][i, j]:.4f}}\", f\"{{adapted_result['cosine'][i, j]:.4f}}\"])\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'best_epoch': artifact_manifest['adapter']['best_epoch']}})\n\n"
                "reloaded = BlipItmPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "parity_images = []\n"
                "for record in test_records[:8]:\n"
                "    with Image.open(record['image']) as photo:\n"
                "        photo.load()\n"
                "        parity_images.append(photo.copy())\n"
                "parity_texts = [query_caption(r) for r in test_records[:8]]\n"
                "before = pipe.score(parity_images, parity_texts)['cosine'].round(4)\n"
                "after = reloaded.score(parity_images, parity_texts)['cosine'].round(4)\n"
                "parity = {{'identical_scores': int((before == after).sum()), 'of': int(before.size)}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "reloaded = None  # free the second copy of the model before any re-run\n"
                "gc.collect()\n"
                "if parity['identical_scores'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the model that was evaluated in Section 8. Re-run from Section 7 (it reloads the pretrained model before adapting), or restart the session and choose Run all.')\n\n"
                "weight_entry = next(entry for entry in MANIFEST['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'pytorch_model.bin pickle, digest-verified, weights_only=True', 'weight_sha256': weight_entry['sha256'], 'hosted_tf_weight_file_not_loaded': HOSTED_TF_WEIGHT_FILE}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'revision': CORPUS_REVISION, 'release': CORPUS_RELEASE, 'license': CORPUS_LICENSE, 'text_columns': list(CORPUS_TEXT_COLUMNS), 'file': CORPUS_FILE, 'pinned_images': len(IMAGE_PINS), 'gallery_row_group': GALLERY_ROW_GROUP}},\n"
                "    'byod': byod,\n"
                "    'splits': disjoint,\n"
                "    'gallery': {{'photographs': len(test_records), 'captions': len(gallery_texts)}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'sanity_checks': checks, 'scenes': {{'names': scene_names, 'sizes': [list(image.size) for image in scene_images], 'rgb_sha256': scene_digests, 'texts': scene_texts, 'correct_text_per_image': correct_text_per_image}}, 'frozen_grid': {{'itm_probability': result['itm_probability'].tolist(), 'cosine': result['cosine'].tolist()}}, 'adapted_grid': {{'itm_probability': adapted_result['itm_probability'].tolist(), 'cosine': adapted_result['cosine'].tolist()}}, 'frozen_report': frozen_scene, 'adapted_report': adapted_scene}},\n"
                "    'adaptation': {{'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'learning_rate': LEARNING_RATE, 'epochs': EPOCHS, 'trainable_text_layers': TRAINABLE_TEXT_LAYERS, 'batch_size': BATCH_SIZE, 'rerank_top_k': RERANK_TOP_K}},\n"
                "    'verdict': verdict,\n"
                "    'comparison': comparison,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** whether any row of the drawn grid changed its ranking, the artifact's tensor count and size, "
        "and the reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>In the recorded runs of the previous notebook version the ranking "
        "did not change — every drawing's own caption still ranked first by both scores — and the fruit scene's ITM "
        "probability went up from 0.278 to 0.350 in the local CPU run. That is one drawing of evidence, not a measurement: the "
        "adaptation trained on photographs, and a change on a cartoon can go either way. The artifact held 58 tensors "
        "(77,202,384 bytes) and reload parity was 64/64: the exported adapter is the model that was evaluated.</details>\n\n"
        "## 10. Your turn — change one thing: a much higher learning rate\n\n"
        "Optional; **Predict → Change → Run → Observe → Explain**. It retrains, so it takes about as long as Section 7 did, "
        "plus one more gallery evaluation in Section 8.\n\n"
        "1. **Predict:** with a learning rate fifty times higher (`1e-3` instead of `2e-5`, the largest `adapt` accepts), "
        "will validation rsum rise faster, rise and then fall, or fall from the first epoch? Which epoch will the selector "
        "keep, and what will Section 8's delta be? Write your guess down, next to the default run's numbers in the Section 8 "
        "run history.\n"
        "2. **Change:** in Section 7 set `LEARNING_RATE = 1e-3`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation rsum again (about 5.816, not the adapted "
        "5.886), then watch the training loss and the validation score; in Section 8, read the verdict and compare the two "
        "rows of the run history; in Section 9, read `best_epoch` in the artifact line.\n"
        "5. **Explain:** in one sentence, why did the selector keep the epoch it kept, and what does that tell you about "
        "the learning rate for fine-tuning a pretrained retriever on 208 photographs?\n\n"
        "<details><summary>Check your reasoning</summary>It falls from the first epoch, and the selector keeps epoch 0 "
        "unless a later epoch climbs back above it. In a local Windows CPU check of this notebook's model code (real "
        "weights, float32, one epoch at `1e-3` from the pretrained model) validation rsum dropped from 5.816 to 5.495: a "
        "step that large overwrites what the pretrained text encoder knew instead of nudging it. No epoch beat the frozen "
        "validation score, so the rule kept epoch 0, the adapted test rsum equalled the frozen one exactly (delta 0.000), "
        "Section 8's verdict says so instead of stopping, and Section 9 exports an adapter whose manifest records "
        "`best_epoch: 0`. That check ran one epoch only, so read your own four-epoch history: if a later epoch did recover "
        "above 5.816, the selector keeps it and the verdict says whether the test gallery agreed. Either way, "
        "validation-based selection is what protects you from a bad setting. If epoch 0 did not show about 5.816, the "
        "model was not reset — restart and **Run all**.</details>\n\n"
        "## Interpretation and limits\n\n"
        "The frozen model is already a competent retriever on photographs it never saw — far above the two non-neural "
        "baselines, and at the ceiling of a 70-photograph gallery — and a bounded fine-tuning of the text encoder's last "
        "two blocks, the ITC projections and the ITM head on 208 VizWiz photographs moved recall over a 391-photograph "
        "gallery by a few points (in the local CPU pre-flight of the previous notebook version rsum 5.024 → 5.162, image → "
        "text R@1 0.742 → 0.791, text → image R@1 0.652 → 0.673, ITM-reranked image → text 0.803 → 0.844; the Kaggle T4 run "
        "of that version agreed within 0.005 rsum) with a 77 MB adapter that reloads to identical scores. That is the claim: "
        "the adaptation contract works end to end on a real out-of-distribution retrieval corpus, and the numbers it "
        "produces are read on six recalls, the ITM re-ranking and per category against two non-neural baselines and the "
        "frozen model rather than in isolation. The gallery size matters more than the adaptation does — the same frozen "
        "model scores rsum 5.72 on 70 photographs and 5.02 on 391 — and the notebook says so.\n\n"
        "The size of that gain is also **optimistic**: the recipe comparisons in the build record were read on the test "
        "gallery, and the gallery size was chosen after the frozen model's test score was seen, so the test split is not "
        "independent evidence for the default settings. Within a run, validation alone chooses the epoch. The gallery is 391 "
        "photographs from two row groups of one shard of one corpus, the validation split that picks the epoch is 40 "
        "photographs whose rsum saturates, the metrics are recall@k over a gallery (own implementations of the COCO "
        "retrieval protocol; none a human judgement), and the ITM pair accuracy barely moved (0.683 → 0.688 on the CPU run, "
        "unchanged on the T4). So a gain here says the contract works, not that the adapted model is better on your "
        "photographs, that it reads the labels VizWiz captions transcribe, or that a match probability is trustworthy — it "
        "still ranks something first for every query, and it can be wrong confidently. Fine-tuning on a narrow corpus can "
        "also erode the model elsewhere; the drawn scenes re-scored in Section 9 are one 3×3 grid of evidence about that, "
        "not a measurement.\n\n"
        "Four things to carry to real data. **Gallery first:** recall@k is only meaningful against a gallery of the "
        "deployment's own size — measure the frozen model over your gallery before any adapted number. **Selection:** choose "
        "settings on validation only, and keep a test gallery you look at once. **Leakage:** keep every record on an image in "
        "one split (the contract does this) and split by photographer or session when your images come from few sources, "
        "never at random over near-duplicate frames. **Negatives:** the in-batch negatives are what teach the ITM head; a "
        "corpus of near-identical photographs gives it hard negatives, a corpus of unrelated ones gives it easy ones and "
        "little to learn.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify the captions and "
        "photographs of a real captioning corpus, validate the demonstrated dataset contract without leakage, execute the "
        "inference contract and a bounded fine-tuning, evaluate against two trivial baselines and the frozen model on an "
        "image-disjoint gallery, and emit the shown machine-readable artifacts — without the repository being reachable. It "
        "does **not** establish benchmark superiority, retrieval quality on any other population or gallery, or production "
        "fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one form field; note the numbers "
        "you want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **A much higher learning rate:** Section 10.\n"
        "- **Deeper re-ranking:** set `RERANK_TOP_K = 10` in Section 6, select Section 6 and choose **Run after**; compare the "
        "re-ranked recalls and the Section 6 time with the default run.\n"
        "- **More trainable blocks:** set `TRAINABLE_TEXT_LAYERS = 4` in Section 7, select Section 7 and choose **Run after**; "
        "compare the trainable-parameter count, the artifact size and the held-out rsum with the default run (the model "
        "card's build sweep found four blocks at 5e-5 no better than the default).\n"
        "- **More epochs:** set `EPOCHS = 6` in Section 7, select Section 7 and choose **Run after**; watch the saturated "
        "validation rsum pick the epoch (the best epoch is kept either way).\n"
        "- **Your own photographs:** BYOD (Section 4, then **Run after**); read the chance baseline over *your* gallery and "
        "the frozen score before the adapted number.\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **\"The isolated environment's Python process exited\".** Usually the runtime ran out of memory. Restart the "
        "session and choose **Run all**; on CPU, close other notebooks first.\n"
        "- **Out of disk, or the checkpoint download stops.** The locked install, the 895 MB checkpoint and the 166 MB of "
        "photographs need a few GB of free space. Start a fresh runtime, or delete `dimer_isolated_env/` and `weights/` from "
        "an earlier attempt.\n"
        "- **A digest or size mismatch in Section 3 or 4.** A download was incomplete or altered; the notebook refuses it "
        "rather than continuing. Run the cell again; never edit the manifest or the image pins.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split left with too few records (at least 12 "
        "records on 12 different images), no or several records files, an image path that does not exist relative to the "
        "records file, an empty or duplicated caption, a duplicate id, a zip over the member or size limit, or a member "
        "outside the upload folder. Fix the zip and run Section 4 with **Run after** again. An empty or cancelled upload "
        "asks you to choose a file or set `BYOD_PATH`.\n"
        "- **Section 8 says \"not improved\" or \"the selector kept epoch 0\".** Not an error: under these settings no "
        "adaptation beat the frozen model on validation, or the kept epoch did not beat it on test. Read the epoch history in "
        "Section 7; the export and reload in Section 9 still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ slightly from the recorded runs.** CPU and GPU arithmetic differ in the low decimals and a close "
        "pair can swap ranks; a few thousandths of rsum or recall between a T4 and a CPU run are expected. Larger differences "
        "on the default settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **ITC (image-text contrastive) score:** the cosine between an image's and a caption's projected embeddings, "
        "computed separately for each (a dual encoder), so a whole gallery can be ranked cheaply.\n"
        "- **ITM (image-text matching) probability:** a classifier head over a joint encoding of one image with one caption "
        "(a fused encoder); more accurate per pair and far more expensive; not calibrated.\n"
        "- **Gallery:** the set of candidates retrieval ranks — here every caption of every test photograph (image → text) "
        "and every test photograph (text → image).\n"
        "- **Recall@k:** the share of queries whose right answer is among the top k; image → text counts a hit when any of "
        "the photograph's own captions is in the top k.\n"
        "- **Median rank:** the middle position of the right answer over all queries; 1 means at least half are found "
        "first.\n"
        "- **rsum:** the sum of the six recalls (R@1/5/10 in both directions), from 0 to 6.\n"
        "- **Re-ranking:** re-ordering the top candidates of the cheap ITC ranking with the expensive ITM head.\n"
        "- **ITM pair accuracy:** how often the ITM head scores a photograph's own caption above the hardest wrong caption by "
        "ITC.\n"
        "- **Hard negative:** a wrong caption (or photograph) that the model already scores high; training on hard negatives "
        "teaches fine distinctions.\n"
        "- **Baseline:** a system with no model (here chance and a colour-keyword lookup) that shows what any useful model "
        "must beat.\n"
        "- **Fine-tuning / trainable blocks:** further training on labelled examples; only the named text-encoder blocks, the "
        "projections and the ITM head may change, the rest stay frozen.\n"
        "- **Learning rate:** how large each training step is; too large and the model forgets what it knew.\n"
        "- **Epoch / validation selection:** one pass over the training pairs; the epoch kept is the one with the highest "
        "validation rsum (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** photographs used to train, to choose the epoch, and to report the final "
        "result once; split by image so no photograph is in two splits.\n"
        "- **Optimistic estimate:** a test score of a configuration whose design was decided by looking at that same test "
        "split.\n"
        "- **Adapter / reload parity:** the saved trained tensors, and the check that a pipeline rebuilt from them gives the "
        "same scores.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- Over this gallery chance reached an rsum of ___, the colour-keyword neighbour ___, the pretrained model ___ and the "
        "adapted model ___; the verdict was ___.\n"
        "- The gain sat mostly in the ___ direction and on the ___ photographs, and the ITM pair accuracy moved ___ because "
        "___.\n"
        "- With a learning rate of 1e-3 (Section 10) the selector kept epoch ___, because ___.\n"
        "- The test gain is optimistic because ___; before trusting this adaptation on my own photographs I would measure ___ "
        "over a gallery of ___ photographs.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/blip-itm-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/blip-itm-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/blip-itm-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model (Salesforce, BSD-3-Clause): https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/salesforce/BLIP\n"
        "- BLIP: Bootstrapping Language-Image Pre-training for Unified Vision-Language Understanding and Generation (Li et al., 2022): https://arxiv.org/abs/2201.12086\n"
        "- Captioning Images Taken by People Who Are Blind (Gurari et al., ECCV 2020; VizWiz-Captions, CC BY 4.0): https://arxiv.org/abs/2002.08565 — data: https://vizwiz.org/tasks-and-datasets/image-captioning/\n"
        "- Align before Fuse: Vision and Language Representation Learning with Momentum Distillation — the ITC + ITM objectives with hard-negative mining (Li et al., 2021): https://arxiv.org/abs/2107.07651\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
